version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - frelance-exchanges
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: on-failure
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - frelance-exchanges

networks:
  frelance-exchanges:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data: