version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - freelance-exchanges
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: on-failure
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - freelance-exchanges
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    restart: on-failure
    container_name: keycloak
    hostname: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_HOSTNAME: localhost
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_DATABASE: keycloakdb
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - freelance-exchanges
    depends_on:
      - db
    links:
      - db

networks:
  freelance-exchanges:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data: