server:
  port: 9001
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/freelance-exchange
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: customer-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: admin
    password: admin
    url: r2dbc:postgresql://localhost:5432/customer_service
  liquibase:
    enabled: true
    change-log: classpath:db/main-change-log.yml
    user: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/customer_service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  auth:
    converter:
      principal-attribute:
        preferred_username
      resource-id:
        freelance-rest-api