server:
  port: 8999
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/freelance-exchange
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: keycloak-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

keycloak:
  realm: freelance-exchange
  clientId: admin-cli
  clientSecret: x74BjLc9OlDiIo8ND3rDPg8Z5c2xgT5L
  urls:
    auth: http://localhost:8080/auth/

jwt:
  auth:
    converter:
      principal-attribute:
        preferred_username
      resource-id:
        freelance-rest-api