server:
  port: 9111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: freelance-rest-api
            client-secret: FKeMnCc6yQWd6w2LK0mhte17Qv4IgNUU
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/freelance-exchange
  main:
    web-application-type:
      reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: freelancer-service
          uri: lb://FREELANCER-SERVICE
          predicates:
            - Path=/api/freelancers/**, /api/resumes/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/ratings/**
        - id: keycloak-service
          uri: lb://KEYCLOAK-SERVICE
          predicates:
            - Path=/api/users/**
      default-filters:
        - name: TokenRelay
        - name: SaveSession