server:
  port: 9020
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/freelance-exchange
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: storage-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  auth:
    converter:
      principal-attribute:
        preferred_username
      resource-id:
        freelance-rest-api
dropbox:
  access-token: ${DROPBOX_TOKEN}